---
- name: check sharedance version
  shell: /usr/local/sbin/sharedanced | sed -n '2p'
  register: current_sharedance_version
  ignore_errors: True

- name: Install dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - libevent-dev
    - gcc
    - make

- name: Download archive
  action: command {{ item }} chdir=/root/
  with_items:
    - wget http://download.pureftpd.org/pub/sharedance/sharedance-{{ sharedance_version }}.tar.gz
    - tar xzfv sharedance-{{ sharedance_version }}.tar.gz
    - rm sharedance-{{ sharedance_version }}.tar.gz
  when: "'{{ sharedance_version }}' not in '{{ current_sharedance_version.stdout }}'"

- name: Install sharedance
  action: command {{ item }} chdir=/root/sharedance-{{ sharedance_version }}
  with_items:
    - ./configure
    - make install-strip
    - mkdir /var/tmp/sharedance
    - rm -rf ../sharedance-{{ sharedance_version }}
  when: "'{{ sharedance_version }}' not in '{{ current_sharedance_version.stdout }}'"

- name: Copy init.d
  template: src=sharedanced.j2 dest=/etc/init.d/sharedanced mode=0755
  notify: restart sharedanced

- name: Start sharedance on boot
  action: command {{ item }} chdir=/etc/init.d/
  with_items:
    - update-rc.d sharedanced defaults
  when: "'{{ sharedance_version }}' not in '{{ current_sharedance_version.stdout }}'"